// Generated by IcedCoffeeScript 108.0.11

/*
	Functions that build the scene
 */

(function() {
  'use strict';
  var addAll, asyncBuildScene, iced, __iced_k, __iced_k_noop,
    __slice = [].slice;

  iced = {
    Deferrals: (function() {
      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) {
          return this.continuation(this.ret);
        }
      };

      _Class.prototype.defer = function(defer_params) {
        ++this.count;
        return (function(_this) {
          return function() {
            var inner_params, _ref;
            inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            if (defer_params != null) {
              if ((_ref = defer_params.assign_fn) != null) {
                _ref.apply(null, inner_params);
              }
            }
            return _this._fulfill();
          };
        })(this);
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  addAll = function() {
    var obj, objects, scene, _i, _len;
    scene = arguments[0], objects = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = objects.length; _i < _len; _i++) {
      obj = objects[_i];
      scene.add(obj);
    }
    return null;
  };

  asyncBuildScene = function(cb) {
    var camera, controls, cubemap, entities, models, objects, ocean, physics, renderer, scene, sky, textures, water, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    scene = create('Scene');
    l("In buildScene(" + scene + ")");
    camera = create('PerspectiveCamera', 60, windowRatio(), 1, 100000).at(0, 10, -30).then('rotateY', Math.PI).then('rotateX', -0.3);
    controls = create('FirstPersonControls', camera)["with"]('movementSpeed', CONF.PLAYER.SPEED)["with"]('lookSpeed', 0);
    renderer = create('WebGLRenderer', {
      antialias: true
    }).then('setSize', window.innerWidth, window.innerHeight).then('setPixelRatio', window.devicePixelRatio);
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/jp/jack/inf/pgtr/proj/src/build.iced"
        });
        asyncLoadTexturesAndModels(['shark', 'white', 'black'], ['shark'], __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              textures = arguments[0];
              return models = arguments[1];
            };
          })(),
          lineno: 28
        }));
        asyncLoadSkybox(CONF.SKYBOX.URLS, CONF.SKYBOX.SIZE, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              sky = arguments[0];
              return cubemap = arguments[1];
            };
          })(),
          lineno: 29
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        objects = SCENE.create({
          envMap: cubemap
        });
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/jp/jack/inf/pgtr/proj/src/build.iced"
          });
          asyncLoadOcean(CONF.OCEAN.URL, renderer, camera, scene, objects.sunlight, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                water = arguments[0];
                return ocean = arguments[1];
              };
            })(),
            lineno: 33
          }));
          __iced_deferrals._fulfill();
        })(function() {
          entities = Entities["new"](scene);
          entities.add('player', createPlayer(createModel({
            geometry: models.shark,
            material: create('MeshPhongMaterial', {
              shininess: 20,
              reflectivity: 0.4,
              color: 0x222222,
              specular: 0x111111,
              map: textures.shark,
              envMap: cubemap
            })
          }).at(-20, 5, 0).scaled(3)));
          entities.player().add(camera);
          physics = new Physics();
          physics.createGround().addRigidBody(entities.player());
          addAll.apply(null, [scene, sky, ocean, entities.player()].concat(__slice.call(objects.objects)));
          return cb({
            scene: scene,
            water: water,
            camera: camera,
            renderer: renderer,
            clock: create('Clock'),
            entities: entities,
            objects: objects,
            physics: physics,
            controls: controls
          });
        });
      };
    })(this));
  };

  window.asyncBuildScene = asyncBuildScene;

}).call(this);
