// Generated by IcedCoffeeScript 108.0.11
(function() {
  'use strict';
  window.l = console.log;

  window.createSunlightControls = function(sunlight) {
    return {
      update: function(_delta) {
        var _ref, _ref1;
        if (Input.sunPitchLower) {
          l("pitch lower");
          sunlight.rotateZ(delta);
          if ((_ref = sunlight.gizmo) != null) {
            _ref.rotateZ(delta);
          }
          sunlight.updateMatrixWorld();
        }
        if (Input.sunPitchRaise) {
          l("pitch raise");
          sunlight.rotateZ(-delta);
          if ((_ref1 = sunlight.gizmo) != null) {
            _ref1.rotateZ(-delta);
          }
          return sunlight.updateMatrixWorld();
        }
      }
    };
  };

  window.createTogglePhysicsControls = function(physics) {
    return window.addEventListener('keyup', function(e) {
      if (e.keyCode == CONF.CONTROLS.togglePhysics) {
        physics.enabled = !physics.enabled;
      }
      return true;
    });
  };

}).call(this);
