// Generated by IcedCoffeeScript 108.0.11

/*
	The object holding the entities, useful for having them available globally
 */

(function() {
  'use strict';
  var Entities;

  Entities = {
    "new": function(scene) {
      this.scene = scene;
      this.entities = {};
      this._i = 0;
      return this;
    },
    add: function(name, e) {
      if (typeof name !== 'string' || name.length < 1) {
        name = "object" + this._i;
        this._i += 1;
      }
      if (this.entities.hasOwnProperty(name)) {
        return;
      }
      l("adding " + name);
      this.entities[name] = e;
      return this;
    },
    destroy: function(name) {
      this.scene.remove(this.entities[name]);
      return this;
    },
    get: function(name) {
      return this.entities[name];
    },
    player: function() {
      return this.entities['player'];
    }
  };

  window.Entities = Entities;

}).call(this);
