// Generated by IcedCoffeeScript 108.0.11

/*
	Event Listeners
 */

(function() {
  'use strict';
  var Input, hdKey;

  Input = {};

  hdKey = function(down) {
    return function(e) {
      var key, val, _ref;
      _ref = CONF.CONTROLS;
      for (key in _ref) {
        val = _ref[key];
        if (e.keyCode == val) {
          l("setting Input[" + key + "]");
          Input[key] = down;
          return;
        }
      }
    };
  };

  window.addEventListener('keydown', hdKey(true), false);

  window.addEventListener('keyup', hdKey(false), false);

  window.Input = Input;

}).call(this);
