// Generated by IcedCoffeeScript 108.0.11

/*
	Functions used for rendering the scene
 */

(function() {
  'use strict';
  var renderLoop;

  renderLoop = function(opts) {
    var animate;
    animate = function() {
      var delta, _ref, _ref1, _ref2, _ref3;
      if ((_ref = opts.stats) != null) {
        _ref.begin();
      }
      requestAnimationFrame(animate);
      delta = opts.clock.getDelta();
      opts.renderer.render(opts.scene, opts.camera);
      if ((_ref1 = opts.entities) != null) {
        if ((_ref2 = _ref1.player()) != null) {
          _ref2.update(delta);
        }
      }
      return (_ref3 = opts.stats) != null ? _ref3.end() : void 0;
    };
    animate();
    return null;
  };

  window.renderLoop = renderLoop;

}).call(this);
