// Generated by IcedCoffeeScript 108.0.11

/*
	Functions dealing with UI
 */

(function() {
  var createStats;

  createStats = function() {
    var stats;
    stats = new Stats();
    stats.domElement.style.position = 'fixed';
    stats.domElement.style.top = '0px';
    stats.domElement.style.right = '0px';
    stats.domElement.style.zIndex = 100;
    return stats;
  };

  window.createStats = createStats;

}).call(this);
