// Generated by IcedCoffeeScript 108.0.11

/*
	Utility functions
 */

(function() {
  'use strict';
  var windowRatio;

  windowRatio = function() {
    return window.innerWidth / window.innerHeight;
  };

  window.windowRatio = windowRatio;

}).call(this);
